name: C/C++ CI

on:
  push:
    branches: [ devel main ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on:
    - ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: autoreconf
      run: autoreconf --force --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
